const TokenTypes = {
  SECTION_START: 'SECTION_START',
  SECTION_END: 'SECTION_END',
  CHOICE_START: 'CHOICE_START',
  CHOICE_END: 'CHOICE_END',
  PROPERTY_KW: 'PROPERTY_KW',
  CONDITIONAL_KW: 'CONDITIONAL_KW',
  OTHER_KW: 'OTHER_KW',
  STRING: 'STRING',
  VARIABLE: 'VARIABLE',
  OPERATOR: 'OPERATOR',
  PUNCTUATION: 'PUNCTUATION',
  NUMBER: 'NUMBER',
  NEWLINE_CHAR: 'NEWLINE_CHAR',
  BOOLEAN: 'BOOLEAN',
  LOOP_KW: 'LOOP_KW',
  FUNCTION_KW: 'FUNCTION_KW',
  RETURN_KW: 'RETURN_KW',
  BREAK_KW: 'BREAK_KW',
  CONTINUE_KW: 'CONTINUE_KW'
}

export default TokenTypes
