const TokenTypes = {
  SECTION_START: 'SECTION_START',
  SECTION_END: 'SECTION_END',
  CHOICE_START: 'CHOICE_START',
  CHOICE_END: 'CHOICE_END',
  PROPERTY_KW: 'PROPERTY_KW',
  CONDITIONAL_KW: 'CONDITIONAL_KW',
  OTHER_KW: 'OTHER_KW',
  STRING: 'STRING',
  VARIABLE: 'VARIABLE',
  OPERATOR: 'OPERATOR',
  PUNCTUATION: 'PUNCTUATION',
  NUMBER: 'NUMBER',
  NEWLINE_CHAR: 'NEWLINE_CHAR',
  BOOLEAN: 'BOOLEAN'
}

export default TokenTypes
